// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace iXlinkerExt
{
    internal sealed partial class Vsix
    {
        public const string Id = "iXlinkerExt.7b1c681c-e091-42c4-87de-d34de60e509a";
        public const string Name = "iXlinker";
        public const string Description = @"Gets details from TwinCAT 3 XAE project and calls CLI for TwinCAT 3 projects providing automated mapping and creating structures based on real EtherCAT hardware configuration.";
        public const string Language = "en-US";
        public const string Version = "1.0.0.4";
        public const string Author = "Tomas Kovac";
        public const string Tags = "INXTON TwinCAT EtherCAT";
    }
}
