// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace iXlinkerExt
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidiXlinkerPackageString = "c4eba0a9-3223-41ab-ba3f-139308432062";
        public static Guid guidiXlinkerPackage = new Guid(guidiXlinkerPackageString);

        public const string guidiXlinkerPackageCmdSetString = "2ceba715-5d41-4032-9847-5d5d95d3adf6";
        public static Guid guidiXlinkerPackageCmdSet = new Guid(guidiXlinkerPackageCmdSetString);

        public const string guidImagesString = "ba314ffa-79bb-4f50-a103-c1bf04470fc3";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int iXlinkerCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}