//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("iXlinker")]
[assembly: AssemblyDescription("CLI for TwinCAT 3 projects providing automated mapping and creating structures based on real EtherCAT hardware configuration.")]
[assembly: AssemblyCompany("INXTON")]
[assembly: AssemblyProduct("iXlinker")]
[assembly: AssemblyVersion("0.1.4.89")]
[assembly: AssemblyFileVersion("0.1.4.89")]
[assembly: AssemblyInformationalVersion("0.1.4-25-CLI-file-version-should-match-the-nuget-package-version.89")]
[assembly: AssemblyCopyright("Copyright ©  2021")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("0b03acc8-2ba8-41f1-bf4d-8ab40cf670ca")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]

[assembly: InternalsVisibleTo("iXlinkerTestHelper")]
[assembly: InternalsVisibleTo("iXlinkerIntegrationTests")]

