//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace TwincatXmlSchemas.TcPlcObject {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TcPlcObject {
        
        private TcPlcObjectBaseType itemField;
        
        private string versionField;
        
        private string productVersionField;
        
        private string fileIdentifierField;
        
        private string fileSignatureField;
        
        public TcPlcObject() {
            this.versionField = "1.1.0.1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClassDiagram", typeof(TcPlcObjectClassDiagram))]
        [System.Xml.Serialization.XmlElementAttribute("DUT", typeof(TcPlcObjectDUT))]
        [System.Xml.Serialization.XmlElementAttribute("EnumerationTextList", typeof(TcPlcObjectEnumerationTextList))]
        [System.Xml.Serialization.XmlElementAttribute("GVL", typeof(TcPlcObjectGVL))]
        [System.Xml.Serialization.XmlElementAttribute("GlobalImagePool", typeof(TcPlcObjectGlobalImagePool))]
        [System.Xml.Serialization.XmlElementAttribute("GlobalTextList", typeof(TcPlcObjectGlobalTextList))]
        [System.Xml.Serialization.XmlElementAttribute("ImagePool", typeof(TcPlcObjectImagePool))]
        [System.Xml.Serialization.XmlElementAttribute("Itf", typeof(TcPlcObjectItf))]
        [System.Xml.Serialization.XmlElementAttribute("Object", typeof(TcPlcObjectObject))]
        [System.Xml.Serialization.XmlElementAttribute("POU", typeof(TcPlcObjectPOU))]
        [System.Xml.Serialization.XmlElementAttribute("RecipeManager", typeof(TcPlcObjectRecipeManager))]
        [System.Xml.Serialization.XmlElementAttribute("Task", typeof(TcPlcObjectTask))]
        [System.Xml.Serialization.XmlElementAttribute("TextList", typeof(TcPlcObjectTextList))]
        [System.Xml.Serialization.XmlElementAttribute("Visu", typeof(TcPlcObjectVisu))]
        [System.Xml.Serialization.XmlElementAttribute("VisuManager", typeof(TcPlcObjectVisuManager))]
        public TcPlcObjectBaseType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProductVersion {
            get {
                return this.productVersionField;
            }
            set {
                this.productVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileIdentifier {
            get {
                return this.fileIdentifierField;
            }
            set {
                this.fileIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileSignature {
            get {
                return this.fileSignatureField;
            }
            set {
                this.fileSignatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectClassDiagram : TcPlcObjectBaseObjType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObjectPropertiesType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LineIdsType {
        
        private LineIdsTypeLineId[] lineIdField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LineId")]
        public LineIdsTypeLineId[] LineId {
            get {
                return this.lineIdField;
            }
            set {
                this.lineIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LineIdsTypeLineId {
        
        private uint idField;
        
        private uint countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImplementationType {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CFC", typeof(ImplementationTypeCFC))]
        [System.Xml.Serialization.XmlElementAttribute("NWL", typeof(System.Xml.XmlNode))]
        [System.Xml.Serialization.XmlElementAttribute("SFC", typeof(System.Xml.XmlNode))]
        [System.Xml.Serialization.XmlElementAttribute("ST", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("StateChart", typeof(System.Xml.XmlNode))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ImplementationTypeCFC {
        
        private System.Xml.XmlNode[] anyField;
        
        private string pageOrientedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PageOriented {
            get {
                return this.pageOrientedField;
            }
            set {
                this.pageOrientedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        CFC,
        
        /// <remarks/>
        NWL,
        
        /// <remarks/>
        SFC,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        StateChart,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseDeclType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseDeclSubType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseObjType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseObjSubType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseImplType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseImplSubType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseDeclImplType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseDeclImplSubType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class TcPlcObjectBaseType {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseDeclSubType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPlcObjectBaseDeclType : TcPlcObjectBaseType {
        
        private string declarationField;
        
        private FolderType[] folderField;
        
        /// <remarks/>
        public string Declaration {
            get {
                return this.declarationField;
            }
            set {
                this.declarationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderType[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FolderType : TcPlcObjectBaseType {
        
        private FolderType[] folderField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderType[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPlcObjectBaseDeclSubType : TcPlcObjectBaseDeclType {
        
        private string folderPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FolderPath {
            get {
                return this.folderPathField;
            }
            set {
                this.folderPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropertyType : TcPlcObjectBaseDeclSubType {
        
        private TcPlcObjectBaseDeclImplSubType[] itemsField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Get", typeof(PropertyTypeGet))]
        [System.Xml.Serialization.XmlElementAttribute("Set", typeof(PropertyTypeSet))]
        public TcPlcObjectBaseDeclImplSubType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PropertyTypeGet : TcPlcObjectBaseDeclImplSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPlcObjectBaseDeclImplSubType : TcPlcObjectBaseDeclImplType {
        
        private string folderPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FolderPath {
            get {
                return this.folderPathField;
            }
            set {
                this.folderPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseDeclImplSubType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPlcObjectBaseDeclImplType : TcPlcObjectBaseType {
        
        private string declarationField;
        
        private ImplementationType implementationField;
        
        private FolderType[] folderField;
        
        /// <remarks/>
        public string Declaration {
            get {
                return this.declarationField;
            }
            set {
                this.declarationField = value;
            }
        }
        
        /// <remarks/>
        public ImplementationType Implementation {
            get {
                return this.implementationField;
            }
            set {
                this.implementationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderType[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PropertyTypeSet : TcPlcObjectBaseDeclImplSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseObjSubType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPlcObjectBaseObjType : TcPlcObjectBaseType {
        
        private System.Xml.XmlElement anyField;
        
        private FolderType[] folderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderType[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPlcObjectBaseObjSubType : TcPlcObjectBaseObjType {
        
        private string folderPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FolderPath {
            get {
                return this.folderPathField;
            }
            set {
                this.folderPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TcPlcObjectBaseImplSubType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPlcObjectBaseImplType : TcPlcObjectBaseType {
        
        private ImplementationType implementationField;
        
        private FolderType[] folderField;
        
        /// <remarks/>
        public ImplementationType Implementation {
            get {
                return this.implementationField;
            }
            set {
                this.implementationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderType[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPlcObjectBaseImplSubType : TcPlcObjectBaseImplType {
        
        private string folderPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FolderPath {
            get {
                return this.folderPathField;
            }
            set {
                this.folderPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectDUT : TcPlcObjectBaseDeclType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectEnumerationTextList : TcPlcObjectBaseType {
        
        private string declarationField;
        
        private System.Xml.XmlElement anyField;
        
        private FolderType[] folderField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public string Declaration {
            get {
                return this.declarationField;
            }
            set {
                this.declarationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderType[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectGVL : TcPlcObjectBaseDeclType {
        
        private TcPlcObjectGVLProperty[] itemsField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        private string parameterListField;
        
        private string addAttributeSubsequentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Property")]
        public TcPlcObjectGVLProperty[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ParameterList {
            get {
                return this.parameterListField;
            }
            set {
                this.parameterListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AddAttributeSubsequent {
            get {
                return this.addAttributeSubsequentField;
            }
            set {
                this.addAttributeSubsequentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectGVLProperty : PropertyType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectGlobalImagePool : TcPlcObjectBaseObjType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectGlobalTextList : TcPlcObjectBaseObjType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectImagePool : TcPlcObjectBaseObjType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectItf : TcPlcObjectBaseDeclType {
        
        private TcPlcObjectBaseDeclSubType[] itemsField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Method", typeof(TcPlcObjectItfMethod))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(TcPlcObjectItfProperty))]
        public TcPlcObjectBaseDeclSubType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectItfMethod : TcPlcObjectBaseDeclSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectItfProperty : TcPlcObjectBaseDeclSubType {
        
        private TcPlcObjectBaseDeclSubType[] itemsField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Get", typeof(TcPlcObjectItfPropertyGet))]
        [System.Xml.Serialization.XmlElementAttribute("Set", typeof(TcPlcObjectItfPropertySet))]
        public TcPlcObjectBaseDeclSubType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectItfPropertyGet : TcPlcObjectBaseDeclSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectItfPropertySet : TcPlcObjectBaseDeclSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectObject : TcPlcObjectBaseObjType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectPOU : TcPlcObjectBaseDeclImplType {
        
        private TcPlcObjectBaseType[] itemsField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        private LineIdsType[] lineIdsField;
        
        private string specialFuncField;
        
        private string addAttributeSubsequentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action", typeof(TcPlcObjectPOUAction))]
        [System.Xml.Serialization.XmlElementAttribute("Method", typeof(TcPlcObjectPOUMethod))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(TcPlcObjectPOUProperty))]
        [System.Xml.Serialization.XmlElementAttribute("Transition", typeof(TcPlcObjectPOUTransition))]
        public TcPlcObjectBaseType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LineIds")]
        public LineIdsType[] LineIds {
            get {
                return this.lineIdsField;
            }
            set {
                this.lineIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SpecialFunc {
            get {
                return this.specialFuncField;
            }
            set {
                this.specialFuncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AddAttributeSubsequent {
            get {
                return this.addAttributeSubsequentField;
            }
            set {
                this.addAttributeSubsequentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectPOUAction : TcPlcObjectBaseImplSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectPOUMethod : TcPlcObjectBaseDeclImplSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectPOUProperty : PropertyType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectPOUTransition : TcPlcObjectBaseImplSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectRecipeManager : TcPlcObjectBaseObjType {
        
        private TcPlcObjectRecipeManagerRecipeDefinition[] recipeDefinitionField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecipeDefinition")]
        public TcPlcObjectRecipeManagerRecipeDefinition[] RecipeDefinition {
            get {
                return this.recipeDefinitionField;
            }
            set {
                this.recipeDefinitionField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectRecipeManagerRecipeDefinition : TcPlcObjectBaseObjSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectTask : TcPlcObjectBaseType {
        
        private uint cycleTimeField;
        
        private uint priorityField;
        
        private TcPlcObjectTaskPouCall[] pouCallField;
        
        private string taskFBGuidField;
        
        private string fb_initField;
        
        private string fb_exitField;
        
        private string cycleUpdateField;
        
        private string postCycleUpdateField;
        
        private FolderType[] folderField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public uint CycleTime {
            get {
                return this.cycleTimeField;
            }
            set {
                this.cycleTimeField = value;
            }
        }
        
        /// <remarks/>
        public uint Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PouCall")]
        public TcPlcObjectTaskPouCall[] PouCall {
            get {
                return this.pouCallField;
            }
            set {
                this.pouCallField = value;
            }
        }
        
        /// <remarks/>
        public string TaskFBGuid {
            get {
                return this.taskFBGuidField;
            }
            set {
                this.taskFBGuidField = value;
            }
        }
        
        /// <remarks/>
        public string Fb_init {
            get {
                return this.fb_initField;
            }
            set {
                this.fb_initField = value;
            }
        }
        
        /// <remarks/>
        public string Fb_exit {
            get {
                return this.fb_exitField;
            }
            set {
                this.fb_exitField = value;
            }
        }
        
        /// <remarks/>
        public string CycleUpdate {
            get {
                return this.cycleUpdateField;
            }
            set {
                this.cycleUpdateField = value;
            }
        }
        
        /// <remarks/>
        public string PostCycleUpdate {
            get {
                return this.postCycleUpdateField;
            }
            set {
                this.postCycleUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public FolderType[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectTaskPouCall {
        
        private string nameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectTextList : TcPlcObjectBaseObjType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectVisu : TcPlcObjectBaseObjType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectVisuManager : TcPlcObjectBaseObjType {
        
        private TcPlcObjectBaseObjSubType[] itemsField;
        
        private ObjectPropertiesType objectPropertiesField;
        
        private string specialFuncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetVisu", typeof(TcPlcObjectVisuManagerTargetVisu))]
        [System.Xml.Serialization.XmlElementAttribute("WebVisu", typeof(TcPlcObjectVisuManagerWebVisu))]
        public TcPlcObjectBaseObjSubType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SpecialFunc {
            get {
                return this.specialFuncField;
            }
            set {
                this.specialFuncField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectVisuManagerTargetVisu : TcPlcObjectBaseObjSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TcPlcObjectVisuManagerWebVisu : TcPlcObjectBaseObjSubType {
        
        private ObjectPropertiesType objectPropertiesField;
        
        /// <remarks/>
        public ObjectPropertiesType ObjectProperties {
            get {
                return this.objectPropertiesField;
            }
            set {
                this.objectPropertiesField = value;
            }
        }
    }
}
